### ISSUE TITLE
Dynamic Workspaces?

### ISSUE THREAD

**Issue by GiovanniCardamone** [mzur/gnome-shell-wsmatrix#103]
it would be nice if workspace can "grows" when require, for example when i try to switch to workspace that doesn't exists yet

is this feature possible to achieve?

**Comment by mzur** [comment]
I'm not sure if this can be implemented. If at all, it would only work by dynamically adding a whole column or a whole row to the grid. Basically the grid would always be one row and one column larger than you actually need. Is this what you had in mind?

**Comment by ebeem** [comment]
the problem with being dynamic in a gird is that it's very hard to know when the user wants to actually expand the workspaces. I will talk about my personal opinion as I believe everyone has their own workflows that they are comfortable with, I have a fixed workspace for each application, some of these applications are configured to actually start on the predefined workspace (e.g. firefox always starts at workspace#2), this allows me to accurately and quickly switch to the right workspace whenever I need to do so.

but having that kind of setup with `3x3` workspaces grid, I can have all workspaces empty except for the last one (workspace#9), and I am expecting it to not expand. Also, I could have all workspaces filled with apps yet I don't need to expand the number of workspaces.

for this feature to land, we need to first think about the possibilities/options that users might need (when should `wsmatrix` expand the workspaces and how does it do that vertically/horizontally)

personally, what comes to my mind when we are talking about a dynamic grid is allowing users to add/remove rows/columns in the workspace overview/popup, here is an example in KDE

![plasma-switcher](https://user-images.githubusercontent.com/25146039/56888715-5883ce00-6a7d-11e9-84e7-21c59015ab9f.png)

the reason why dynamic is easy in normal workspaces and confusing in girds is that grids need to expand rows/columns, this will result in multiple amounts of workspaces being added. For those who memorize their workspace order and where applications are running, adding a set of workspaces will reduce the accuracy of switching to the right workspace (e.g. if 3x3 workspace expands to 4x3 with wrap around enabled, moving from workspace#8 to workspace#2 will require going down 2 times instead of once). However, those who use the popup/overview will have no issues at all as far as I am concerned.

to plan this right, we need to answer a lot of questions first so someone starts the development. I am not sure how dynamic is going to work on a grid tbh. If you have time, please provide us with more details (use cases/scenarios) of how and when the extension is supposed to dynamically expand the number of workspaces.

**Comment by mzur** [comment]
@ebeem raised many valid points (thanks!) If dynamic workspaces can only be done "right" with significant effort and at the same time by moving farther away from the default GNOME UI, I would vote against adding such a feature to this extension.
