### ISSUE TITLE
Visual bug with Materia theme

### ISSUE THREAD

**Issue by AlexWayfer** [mzur/gnome-shell-wsmatrix#12]
Hello!

Unfortunately, I don't see borders around selected workspace thumbnail with [Materia theme](https://github.com/nana-4/materia-theme):

![image](https://user-images.githubusercontent.com/6510020/56129780-bd262f80-5f8b-11e9-823a-22b2b89ecbee.png)

Can it be fixed/improved in this extension, or is it bug in theme?

Thank you.

**Comment by mzur** [comment]
It's probably an issue with the theme. This extension uses the same [workspace thumbnail indicator](https://github.com/mzur/gnome-shell-wsmatrix/blob/09f557a3659b20c587cd0aea19a3947d8b684a04/wsmatrix%40martin.zurowietz.de/WorkspaceSwitcherPopup.js#L138) element that is displayed in the workspace list on the right of the activity overview. If you can't see the active workspace indicator there, the theme has to add a style for it.

**Comment by AlexWayfer** [comment]
Oh, OK.

It looks like this:

![image](https://user-images.githubusercontent.com/6510020/56133230-94566800-5f94-11e9-94e0-0170d7379f43.png)

And I saw white stripe at the thumbnails bottoms.

So, I'm not sure, how best to handle this. 

Maybe another color of background?

**Comment by mzur** [comment]
So the indicator is there after all but it is invisible against the white background of the workspace switcher popup. It's unusual that the popup has a different style than the workspace list in the activity overview. Maybe you can persuade the guys behind the theme to change that.

On the other hand, this is somewhat an issue with this extension, too, since it does not use the default way to indicate the active workspace in the workspace switcher popup. The default (as far as I know) is to show an arrow down or arrow up overlay on the icon of the active workspace. But since there is no arrow right or left overlay, I chose not to use that.

Maybe this situation could be improved with an additional settings option. The option would either activate the workspace thumbnail indicator (as it is now) or dim the workspace thumbnails of inactive workspaces with a lower opacity. What do you think of this solution?

**Comment by AlexWayfer** [comment]
> On the other hand, this is somewhat an issue with this extension, too, since it does not use the default way to indicate the active workspace in the workspace switcher popup. The default (as far as I know) is to show an arrow down or arrow up overlay on the icon of the active workspace. But since there is no arrow right or left overlay, I chose not to use that.

The default pop-up with Materia theme:

![image](https://user-images.githubusercontent.com/6510020/56145186-798fed80-5fac-11e9-88b5-fb848f27f3b9.png)

With default GNOME theme, Adwaita:

![image](https://user-images.githubusercontent.com/6510020/56145249-9f1cf700-5fac-11e9-84d5-1a5591397b55.png)

So, there are different colors. Without thumbnails. Maybe, this extension can use the background color as background, and the "active workspace" color (blue) as color for border around active workspace.

**Comment by mzur** [comment]
Just so you know, I haven't forgotten this issue. I'm not 100 % convinced by the idea with the blue border as this might prevent any customizability by themes. I'll get back to this issue eventually but the possible merge with Workspace Grid has a higher priority right now. Please feel free to create a more complete visual mockup of your proposal or implement a prototype.

**Comment by ebeem** [comment]
please try pull request #20 
I think this will fix your problem, let us know what happens.

**Comment by mzur** [comment]
I was wondering if we could use the style of indicator box in the "application window switcher", instead. It might work for the workspaces, too.

![image](https://user-images.githubusercontent.com/2457311/58621356-6ff6e680-82c9-11e9-8f2a-6f6b14a081b8.png)

**Comment by ebeem** [comment]
since this is still open, I personally like the way [Dash To Dock](https://github.com/micheleg/dash-to-dock) handles this issue. In preferences, an option is available to customize the look of the extension or just use the built-in theme settings. 
I can't think of a better solution as `GNOME` themes have no standards, and some themes just break other apps/extensions (same as `gtk` themes).

![Screenshot from 2019-08-31 02-30-00](https://user-images.githubusercontent.com/25146039/64055818-8bf37800-cb97-11e9-8dc1-4646dfecce0f.png)

**Comment by mzur** [comment]
That would certainly be an option. The custom color could change both the active thumbnail indicator as well as the active workspace indicator if thumbnails are disabled (although this should have a proper style by the theme).

This extension has grown to incorporate quite a few features by now. I would like it not to become too complicated to maintain (and to use). I think after #49, #50 and this color chooser we can put a stop to new features.
