### ISSUE TITLE
Feature Request: Super + W A S D

### ISSUE THREAD

**Issue by Gideon-Felt** [mzur/gnome-shell-wsmatrix#133]
instead of just super + w can it be super and one of the WASD keys, if you type super +w open the grid and move up then any further was keystrokes, would navigate further? it would be nice for speedy navigation especially on a laptop with compressed arrow keys. and it would be one-handed navigation. Material shell creator implemented something along these lines.

**Comment by Gideon-Felt** [comment]
well, I discovered how to do it via gsettings, but this config would be really nice out of the box, it took me quite a while to learn to use gsettings with the right syntax for keybindings.

**Comment by mzur** [comment]
Thanks for your interest in this extension. We have a [wiki](https://github.com/mzur/gnome-shell-wsmatrix/wiki/Custom-keyboard-shortcuts) that describes how to change the keyboard shortcuts. I'd rather leave it at that because everyone has their own preferences and there will always be someone who is not satisfied with the defaults.

**Comment by ericwooley** [comment]
As I understand what @Gideon-Felt  is saying, they are looking for one key combo to switch right? Instead of opening the overview then switching? 

I'm trying to do switch workspaces in one step as well, how did you set it up via gsettings? I added key combos as described in the wiki, but they only work when the overview is open.

**Comment by mzur** [comment]
The shortcuts in the wiki are the ones provided by this extension only. There are default GNOME shortcuts, too. You are probably looking for `switch-to-workspace-down` (`-up`, `-right`, `-left`).

**Comment by ericwooley** [comment]
Ah, i see, thanks. 

For anyone else who finds this from google, you can edit the shortcuts for regular left, right, up, and down in dconf-editor `/org/gnome/desktop/wm/keybindings/switch-to-desktop-<DIRECTION>`, where  DIRECTION is up, left, right, down.
