### ISSUE TITLE
workspace matrix and multiple monitors

### ISSUE THREAD

**Issue by RafalSkolasinski** [mzur/gnome-shell-wsmatrix#157]
I am using this extensions together https://extensions.gnome.org/extension/921/multi-monitors-add-on/ for multi-monitor setup. 

Though workspaces behaves like matrix on all monitors in the overview of non-primary monitor they are arranged linearly, see following screenshot

![image](https://user-images.githubusercontent.com/10928117/118054540-5ba93880-b37e-11eb-8961-d68b4e879af5.png)

**Comment by ebeem** [comment]
in `GNOME` prior to 40, only the primary display had the workspace thumbnails in the overview. An extension can add the overview to other displays, so this will not be supported by this extension. 
However, since `GNOME 40` now shows the workspace thumbnails in the overview for all monitors, this is planned to be supported in #152.
