### ISSUE TITLE
Matrix in ubuntu 21.10 and gnome mouse events

### ISSUE THREAD

**Issue by icegood** [mzur/gnome-shell-wsmatrix#197]
Pre-conditions: 
1) extension v 31 is installed over gnome 40 in ubuntu 21.10
2) 9 static workspaces are defined

Use case:

1) Locate mouse button over left bpanel with applications and start to scroll

Expected result: either no actions happen or 'smart' scroll within workspaces occur in matrix mode.

Actual result: occurs 'native' scrolling within desktops. Moreover, not all WS's are scrolled: scrolled only one horizontal line defined in matrix for which active workspace belongs to. I.e. if active workspace in 3x3 is #6 then 4-5-6 are reachable within scrolling. See picture below

![ScrollMouseOverLeftPanel](https://user-images.githubusercontent.com/18632233/147754559-7c02e9fe-b31e-40fc-a5e3-4042d073af4c.png)

**Comment by ebeem** [comment]
Yup, I noticed that scrolling in the overview skips the rows, but where are you scrolling your case?
Is this some other extension you have installed? I am not aware of a way to scroll workspaces with the mouse wheel other than the overview.

**Comment by icegood** [comment]
Scrolling is on 'dash panel' with applications as it was mentioned in the use case. Sorry, the mouse arrow is not captured by screenshot.

**Comment by ebeem** [comment]
I think Ubuntu uses this extension 
https://github.com/micheleg/dash-to-dock/
If it's the one you're using, then it's probably hard to fix as integration between extensions isn't always easy.
So if I am not mistaken, this dash you have is not part of `gnome-shell` right? its just an extension.

**Comment by icegood** [comment]
no, i've just installed this extension to see if something changes. Same effect

**Comment by icegood** [comment]
Unistalled back. Played a bit with build-in ones. Found "Ubuntu dock" is a one!

**Comment by icegood** [comment]
https://extensions.gnome.org/extension/1300/ubuntu-dock/

**Comment by ebeem** [comment]
Yes, what I am trying to say is, because `dash-to-dock` or the `dash panel` or `ubuntu-dock` (which is a fork of `dash-to-dock`) you have is a 3rd party extension (not `gnome-shell` built-in). Then it's hard to make it integrate well with `wsmatrix` (this extension). We will have to basically add a lot of code to ensure that all the available extensions are integrated well which is out of the scope of `wsmatrix`.

Of course there's nothing stopping you from modifying the code to get the behavior you want, but that's probably something you will need to tweak in `dash-to-dock` and not `wsmatrix`.

**Comment by icegood** [comment]
OK, tnx. Anyway now I know a reason...

**Comment by ebeem** [comment]
Sure, thanks for reporting this.
