### ISSUE TITLE
Wraparound gives wrong animation

### ISSUE THREAD

**Issue by TheBlackKoala** [mzur/gnome-shell-wsmatrix#25]
The wraparound animation on the edges gives animation the wrong way.
When moving left from workspace one to three (if you have three workspaces in a row) then the animation should be to the left but it is to the right.

**Comment by mzur** [comment]
This can't be fixed by this extension, I'm afraid. The way GNOME handles this, the workspaces are one big virtual screen. And on this screen the rightmost workspace is always located to the right of the leftmost workspace. If this should be implemented like those infinite JavaScript carousels, the workspaces would have to be duplicated for the sake of the animation. I'm not even sure this can be done by an extension at all.
