### ISSUE TITLE
Feature: Unity style expo

### ISSUE THREAD

**Issue by goodwillcoding** [mzur/gnome-shell-wsmatrix#3]
I am sure if this is the right request, but have you given any though to Unity style Expo toggle where the grid of workspace becomes the fullscreen view and windows can be dragged between different workspaces?

**Comment by mzur** [comment]
I thought about it since GNOME currently has no easy way (that I know of) to switch between workspaces with single hand shortcuts. The Unity Expo allowed that. That said, the GNOME overview screen (Super+S) has a similar display at the right where you can drag windows between workspaces. In addition to that, I don't have the time and intention to develop any new features for this extension. But if anyone is willing, I'd gladly review and accept pull requests.

**Comment by goodwillcoding** [comment]
@mzur I've been looking into this myself (also had difficulty with workspace grid). If I can figure it out, I'll PR it :)

**Comment by mzur** [comment]
I'll close this for now. You can still feel free to submit a PR.
