### ISSUE TITLE
Active workspace in workspace overview without thumbnails

### ISSUE THREAD

**Issue by mzur** [mzur/gnome-shell-wsmatrix#48]
If workspace thumbnails are disabled, the currently active workspace is not shown in the workspace overview (see [here](https://github.com/mzur/gnome-shell-wsmatrix/pull/44#issuecomment-524160053)). The highlighting only appears when the workspaces are switched.

**Comment by ebeem** [comment]
the piece of code that highlights the indicator checks active workspace this way

```Javascript
if (i === this._activeWorkspaceIndex && (this._direction == Meta.MotionDirection.UP || this._direction == Meta.MotionDirection.LEFT)) {
   indicators[i].style_class = 'wsmatrix ws-switcher-active-up';
} else if (i === this._activeWorkspaceIndex && (this._direction == Meta.MotionDirection.DOWN || this._direction == Meta.MotionDirection.RIGHT)) {
   indicators[i].style_class = 'wsmatrix ws-switcher-active-down';
}
```

there is no **fallback** in case the direction is undefined, which is the case in showing the workspace overview. Since the stylesheet already make the background image none, I am not actually sure if there is going to be any difference between the `ws-switcher-active-up` and `ws-switcher-active-down` classes in any theme.

So maybe the workaround will be something like this

```Javascript
if (i === this._activeWorkspaceIndex && (this._direction == Meta.MotionDirection.UP || this._direction == Meta.MotionDirection.LEFT)) {
   indicators[i].style_class = 'wsmatrix ws-switcher-active-up';
} else if (i === this._activeWorkspaceIndex) {
   indicators[i].style_class = 'wsmatrix ws-switcher-active-down';
}
```

**Comment by mzur** [comment]
I agree. Your suggestion should work fine.
