### ISSUE TITLE
Feature-Request: Workspace-layout-mini-view-overlay should only dissappear once I let go of the modifier key for switching desktops

### ISSUE THREAD

**Issue by packoman** [mzur/gnome-shell-wsmatrix#59]
I would really love to see the following:

Make it configurable, so that the workspace-layout-mini-view-overlay only disappears, once you let go of Ctrl+Alt after hitting arrow-button+Ctrl+Alt (perhaps combined with the configurable timeout).

This is the behavior of Unity and in Unity it let me orientate myself and find the workspace that I want to go to and then go to it directly in a single go (in case I do not know, which workspace out of my head).

Let me know if anything is unclear. Thanks.

**Comment by ebeem** [comment]
I actually think the `modifier key release` approach (the one this issue mentions) is much better than the `timeout` approach, because the `modifier key release` approach is already used in the `language-switcher` popup, the `application-switcher` popup, and probably many other components of `GNOME`. I looked at this already, the trick is just to get a `key-release-event` to work.

Unfortunately , it didn't work for me. I will give it another try sometime later and let you know how it goes.

**Comment by apirrone** [comment]
I agree !

**Comment by mzur** [comment]
I'd like this, too. This can be a new switch in the settings that disables the timeout.

**Comment by ebeem** [comment]
#76 almost fixes this, needs some more work.

**Comment by mzur** [comment]
The discussion can continue in #76.
