### ISSUE TITLE
Can't move windows between workspaces

### ISSUE THREAD

**Issue by EmmanuelMess** [mzur/gnome-shell-wsmatrix#61]
Moving a window half out of the screen to the left or right doesn't half move it to the workspace to the left or right like on Unity.

**Comment by ebeem** [comment]
`GNOME` does NOT provide such a feature. If my understanding is correct, workspaces are not linked in any way with each other, using this extension, you only display them as a grid rather than the default vertical layout.

I don't think the scope of this extension includes a `workspace-manager` replacement, maybe @mzur can give more details on this, we should probably define the extension's scope in the `README`.

Just briefly, I am explaining the workflow of `GNOME` here, `GNOME` expects you to have tiling windows in each workspace and expects you to mainly use shortcuts to switch between workspaces or move windows across workspaces (you can move windows by right clicking their toolbars).

the default shortcuts for moving between workspaces are: `<ctrl>`+`<alt>`+`<arrow_key>` 
the default shortcuts for moving windows across workspaces are: `<ctrl>`+`<alt>`+`<shift>`+`<arrow_key>` 
where `<arrow_key>` can be either the up/down/right/left arrow key.

**Comment by EmmanuelMess** [comment]
That breaks with Android Virtual Device, where you need to do it twice to move the emulator. Maybe that should be the issue?

**Comment by ebeem** [comment]
Then maybe you need to change the shortcuts of `AVD` or your `GNOME` shortcuts.
You can also always go to the overview and move windows to other workspaces from there.

**Comment by EmmanuelMess** [comment]
> Then maybe you need to change the shortcuts of `AVD` or your `GNOME` shortcuts.

What do you mean? The shortcuts "work", they move half of the AVD at a time.

> You can also always go to the overview and move windows to other workspaces from there.

Good point, haven't tried.

**Comment by mzur** [comment]
This extension is not meant to emulate the features of Unity in GNOME. The move window shortcut only works for a single window. If your application consists of multiple windows, you have to move each window separately.

**Comment by mzur** [comment]
Please reopen if this is still relevant.
