### ISSUE TITLE
Crash on Gnome 3.34.1 on Archlinux

### ISSUE THREAD

**Issue by daniel-k** [mzur/gnome-shell-wsmatrix#77]
I'm not entirely sure about the real cause why the extension is crashing now. I updated my system today and now it's not working anymore. However, there were announcements about an update to this extension that I ignored for some time already. So maybe the system/Gnome update today also led to an update to the extension?

I already tried re-installing the application but to no avail.

Current Gnome shell version:
gnome-shell 1:3.34.1+12+ga43c22e3a-1

The settings of extension wsmatrix@martin.zurowietz.de had an error:
```
Error: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
```

Stack trace:
```
Settings@/home/daniel/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/Settings.js:23:5
buildPrefsWidget@/home/daniel/.local/share/gnome-shell/extensions/wsmatrix@martin.zurowietz.de/prefs.js:144:19
_showPrefs@resource:///org/gnome/shell/extensionPrefs/main.js:57:22
_extensionsLoaded@resource:///org/gnome/shell/extensionPrefs/main.js:320:13
_scanExtensions/<@resource:///org/gnome/shell/extensionPrefs/main.js:298:13
asyncCallback@resource:///org/gnome/gjs/modules/overrides/Gio.js:132:13
main@resource:///org/gnome/shell/extensionPrefs/main.js:707:5
@<main>:1:43
```

**Comment by ViggoGaming** [comment]
I got the same error.. Is there any fix for it?

**Comment by kevinhwang91** [comment]
https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/551
just rollback gjs

**Comment by ebeem** [comment]
I think something is wrong, my Arch runs `gjs 1.58.2` and `GNOME Shell 3.34.1`
I have no problems with preferences at all, will do a fresh install test and let you know what happens.

there is no major release yet, code changes are expected to be needed only when a major GNOME version is released, so I think there is a buggy package in the Arch Repo.

**Comment by ebeem** [comment]
the problem happened after I upgraded these packages
```
[2019-11-25T18:09:24+0300] [ALPM] upgraded iana-etc (20191030-1 -> 20191123-1)
[2019-11-25T18:09:24+0300] [ALPM] upgraded libxml2 (2.9.9-6 -> 2.9.10-1)
[2019-11-25T18:09:26+0300] [ALPM] upgraded libxslt (1.1.33-1 -> 1.1.34-1)
[2019-11-25T18:09:26+0300] [ALPM] upgraded calibre (4.3.0-3 -> 4.4.0-1)
[2019-11-25T18:09:26+0300] [ALPM] upgraded librsvg (2:2.46.3+6+g4735bd07-1 -> 2:2.46.4-1)
[2019-11-25T18:09:26+0300] [ALPM] upgraded libgusb (0.3.0-1 -> 0.3.1-1)
[2019-11-25T18:09:26+0300] [ALPM] upgraded libnm (1.20.6-1 -> 1.20.8-1)
[2019-11-25T18:09:27+0300] [ALPM] upgraded gnome-music (1:3.34.1-2 -> 1:3.34.2-1)
[2019-11-25T18:09:27+0300] [ALPM] upgraded gnome-software (3.34.1-1 -> 3.34.2-1)
[2019-11-25T18:09:27+0300] [ALPM] upgraded lib32-libxml2 (2.9.9-3 -> 2.9.10-1)
[2019-11-25T18:09:31+0300] [ALPM] upgraded linux (5.3.12.1-1 -> 5.3.13.1-1)
[2019-11-25T18:09:36+0300] [ALPM] upgraded linux-headers (5.3.12.1-1 -> 5.3.13.1-1)
[2019-11-25T18:09:41+0300] [ALPM] upgraded linux-lts-headers (4.19.85-1 -> 4.19.86-1)
[2019-11-25T18:09:41+0300] [ALPM] upgraded lollypop (1.2.13-1 -> 1.2.15-1)
[2019-11-25T18:09:41+0300] [ALPM] upgraded networkmanager (1.20.6-1 -> 1.20.8-1)
[2019-11-25T18:09:41+0300] [ALPM] upgraded syslinux (6.04.pre2.r11.gbf6db5b4-2 -> 6.04.pre2.r11.gbf6db5b4-3)
```

**Comment by chrisjbillington** [comment]
Issue is being addressed in gjs:

https://gitlab.gnome.org/GNOME/gjs/issues/288

They will make an emergency release that should resolve the problem in gnome-shell 3.34.

Watch the gjs bug report to see whether action will need to be taken for the gnome 3.36 release.

**Comment by ptomato** [comment]
Hi, I have made an emergency GJS 1.58.3 release, that should make things work again for the moment. Sorry about this; I didn't realize there was any possibility that the condition being checked for could have worked at all! I thought we were just replacing a cryptic error message with a clear one.

That said, [this class](https://github.com/mzur/gnome-shell-wsmatrix/blob/master/wsmatrix%40martin.zurowietz.de/Settings.js) seems to have been doing something for a while that wasn't intended, and so may be broken in subtle ways, for example because parent methods aren't overridden correctly, or when connecting to signals. Unfortunately we have to use `GObject.registerClass()` on subclasses of `GObject.Object` for things to work correctly. So we are going to put back the check starting in GNOME 3.36, and I am considering re-adding it as a warning (instead of an exception) in GJS 1.58.4 next month.

Therefore I would recommend fixing the code even for GNOME 3.34, to avoid subtle breakage that your extension might be suffering from even right now. It should be fairly straightforward to fix. In this particular case I'd recommend using composition instead of inheritance or even just using `Gio.Settings` directly, because starting with GNOME 3.34 you should now no longer need to check if the schema exists (see release notes at https://gitlab.gnome.org/GNOME/gjs/-/tags/1.57.2), but that's just my personal preference. If you prefer to fix it in the least invasive way possible, this (untested) patch should do the trick:
```diff
 const WsMatrix = imports.misc.extensionUtils.getCurrentExtension();
-const Gio = imports.gi.Gio;
+const {Gio, GObject} = imports.gi;
 const GioSSS = Gio.SettingsSchemaSource;
 
-var Settings = class Settings extends Gio.Settings {
-  constructor(schema) {
+var Settings = GObject.registerClass(
+class Settings extends Gio.Settings {
+  _init(schema) {
     let schemaDir    = WsMatrix.dir.get_child('schemas');
     let schemaSource = null;
 
     if (schemaDir.query_exists(null)) {
       schemaSource = GioSSS.new_from_directory(schemaDir.get_path(), GioSSS.get_default(), false);
     } else {
       schemaSource = GioSSS.get_default();
     }
 
     let schemaObj = schemaSource.lookup(schema, true);
 
     if (!schemaObj) {
       let message = 'Schema ' + schema + ' could not be found for extension ' + WsMatrix.metadata.uuid;
       throw new Error(message + '. Please check your installation.');
     }
 
-    super({ settings_schema: schemaObj });
+    super._init({ settings_schema: schemaObj });
   }
-};
+});
```

**Comment by daniel-k** [comment]
Thank you @ptomato and everyone involved! Archlinux already [picked up your emergency release](https://www.archlinux.org/packages/extra/x86_64/gjs/). You are awesome guys :heart:
