### ISSUE TITLE
[Feature] Allow to move between workspaces horizontally by keyboard shortcuts

### ISSUE THREAD

**Issue by AlexWayfer** [mzur/gnome-shell-wsmatrix#8]
But I'm not sure, because there are only "up" and "bottom" directions in System Settings.

So, it can be something configurable only in the extension.

**Comment by mzur** [comment]
This already works with the left and right arrows. But there is a bug in a newer Mutter version that breaks this. The fix is under way but has not been released yet as far as I know. See #4 for more details. There is also a [link](https://github.com/zakkak/workspace-grid/issues/88#issuecomment-435037672) on how to patch your own version of Mutter.

**Comment by AlexWayfer** [comment]
OK, thanks!

(Oh, this `mutter`!)

**Comment by vc7ee** [comment]
How would one do this on Fedora?
