### ISSUE TITLE
hide app from taskbar

### ISSUE THREAD

**Issue by cyberhck** [mzur/gnome-shell-wsmatrix#81]
Even though slack on my desktop is at 2nd row and 2nd column in my matrix of workspace, it still shows on the taskbar,

what I like is that it hides from Alt + Tab list of applications, but still having that one on is a little sad.

**Comment by ebeem** [comment]
can you please provide more information?
what `gnome-shell` version are you using? as far as I am concerned, `gnome-shell` does NOT show the taskbar anymore. Unless you're using an extension for that, you're not gonna be able to even see the apps in the taskbar (or so I believe).

with that being said, the extension you use should be updated to show only apps on the current workspace. Workspaces is a feature in gnome-shell, this extension just improves the way workspaces are organized, your apps are hidden from `Alt+Tab` because that extension is configured to do so and it will work whether you have `WsMatrix` enabled or not.

![Screenshot from 2019-12-01 18-49-22](https://user-images.githubusercontent.com/25146039/69916414-c78a3080-146b-11ea-9abd-0a7870dc28f7.png)



Please correct me if I made wrong assumptions.

**Comment by cyberhck** [comment]
actually I'm on latest ubuntu, and not even sure which version of gnome it's using, ubuntu has this side bar thing:
![image](https://user-images.githubusercontent.com/3640284/69917375-9de6fe80-1497-11ea-8ec8-27f5f1f17562.png)

thanks for the prompt reply

**Comment by ebeem** [comment]
oh, I see
This is based on an extension called [dash-to-dock](https://extensions.gnome.org/extension/307/dash-to-dock/), Ubuntu forked this extension or something (I am not so up-to-date with Ubuntu news).
in this extension, there is an option to do that.

![Screenshot from 2019-12-01 20-10-10](https://user-images.githubusercontent.com/25146039/69917409-bbf03700-1476-11ea-82e4-26f347bfb4a4.png)

I am not sure whether Ubuntu does provide this option or not, in case you need this feature and it does not exist in Ubuntu's [dash-to-dock](https://extensions.gnome.org/extension/307/dash-to-dock/), then consider disabling it and replacing it with the original [dash-to-dock](https://extensions.gnome.org/extension/307/dash-to-dock/).
