### ISSUE TITLE
Allow mouse clicks to choose workspace in the Workspace Selector.

### ISSUE THREAD

**Issue by noel-yap** [mzur/gnome-shell-wsmatrix#88]
The Workspace Selector currently isn't processing mouse clicks to choose the workspace.

**Comment by ebeem** [comment]
some help is needed for this feature, the idea is to try to bring the matrix in overview and display it in the popup as it already includes all kind of functions we need.

#60 mentions drag and drop also which can be fixed with this issue if the overview approach is followed.

**Comment by recolic** [comment]
I'm using the new gnome 40 version. I noticed that, while switching workspace with keyboard `ctrl+alt+right/left/up/down`, the mouse cursor is usually on the popup. 
Then, if I slightly move the mouse cursor, it immediately switches to a completely unwanted workspace. Releasing `ctrl` before `alt` also causes the same error. 

I'm not sure if other testers have similar experience... Maybe it's better to limit this feature to `mouse click`, instead of `mouse movement` or `releasing ctrl before alt`.

**Comment by ebeem** [comment]
@recolic thanks for reporting, this was fixed by only selecting workspace if mouse is moved.
please let's discuss any issue with the current implementation (if any) in the PR #152.
